env: "local"
storage_path: "./storage"

http_server:
  address: "localhost:8082"
  timeout: "4s"
  idle_timeout: "60s"

database:
  dsn: "postgres://postgres:postgres_password@localhost:5433/messenger_db?sslmode=disable"