env: "local"
storage_path: "./storage"
token_secret: "my-secret"

http_server:
  address: "localhost:8082"
  timeout: "4s"
  idle_timeout: "60s"

database:
  dsn: "postgres://postgres:postgres_password@localhost:5433/messenger_db?sslmode=disable"

redis:
  address: "localhost:6379"

minio:
  endpoint: "localhost:9000"
  access_key_id: "minio_user"
  secret_access_key: "minio_password"
  bucket: "images"
  use_ssl: false